# Railway deployment configuration
[phases.setup]
nixPkgs = ["nodejs_18", "python3", "python3Packages.pip"]

[phases.install]
cmds = ["npm ci", "cd backend && pip install -r requirements.txt --break-system-packages"]

[start]
cmd = "cd backend && python -m uvicorn main_diagnostic:app --host 0.0.0.0 --port $PORT"